[package]
name = "crane-test-crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "crane-bug"
path = "src/main.rs"

[dependencies]
bzip2-sys = "0.1.11"
